### ISSUE TITLE
Testing on WAV files from Youtube?

### ISSUE THREAD

**Issue by maximtolea** [x4nth055/emotion-recognition-using-speech#20]
Hello,

I wanted to use this repository for calling predictions and prediction probabilities on .wav files I'm getting from the internet. I've been using converted youtube audio clips (in the final form of .wav). For some reason, basic predictions aren't being done on these files. I wanted to know if you could explain how one should properly test these new WAV files. For the time being, I've just been following example 2 in the README, downloading the files, and putting them in their own folder within the emotion-recognition-using-speech one. Is there anything in the code I should modify to be able to use this program on wav files converted from Youtube?

**Comment by maximtolea** [comment]
I haven't changed anything in the code. I have written some scripts for my own usage. The program works fine for the provided .wav files in the data sets. However, in my case, the program terminates without any prediction or probability score being printed in the console.

**Comment by x4nth055** [comment]
Hi @maximtolea ,

Before using any outsider audio file, you need to first convert its sample rate to 16000 and mono channel, I've provided the script `create_wavs.py` for that case. Note that you'll need to have [`ffmpeg`](https://www.ffmpeg.org/) installed in your machine in order to properly convert the audio files.

Hope this helps. Let me know when this solves your issue.

**Comment by x4nth055** [comment]
Hey again,

I've updated the code to automatically convert to the appropriate format when using the `predict()` method. Pull the repo again and check it out!

Thanks, closing the issue.
